name: Create README.md
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  readme:
    name: udpate readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get file names and write to README.md
        run: |
          echo "## cheatsheet" > README.md
          find . -name "*.md" -and -not -name "README.md" | cut -c 3- | sort | sed -e "s/^/- /" >> README.md

      - name: commit README.md
        run: |
          git config --global user.name "Luca Ionescu"
          git config --global user.email "lucaionescu@users.noreply.github.com"
          git add README.md
          git commit -m "update README.md [skip ci]"
          git push
